use_default_settings: true
search:
  safe_search: 2
  formats:
    - html
    - json
server:
  secret_key: "local-private-search-instance-change-before-public-exposure"
  limiter: false
  public_instance: false
  image_proxy: false
